platform :ios, "11.0"
use_frameworks!
inhibit_all_warnings!

target 'ChatKeepcoding' do
    
  pod 'MessageKit'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Database'
  pod 'FirebaseStorage'
  pod 'Kingfisher'
  pod 'Firebase/Messaging'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'MessageKit'
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.0'
              end
          end
      end
  end

end
